### ISSUE TITLE
求助大神：使用CPU模式，一旦“上传音色”后单击“生成”，立即提示如下错误，具体修改哪个文件可以解决这个问题呢？

### ISSUE THREAD

**Issue by githubberers** [CCmahua/ChatTTS-Enhanced#16]
使用CPU模式，一旦“上传音色”后单击“生成”，立即提示如下错误：
Traceback (most recent call last):
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "E:\Chat-TTSV3\webui\output_option.py", line 95, in generate_audio
    original_audio_output,enhanced_audio_output, text = audio_pre_processor(audio_pre_Process_Params,enhance_parms,CHAT)  File "E:\Chat-TTSV3\processors\audio_processor.py", line 38, in audio_pre_processor
    rand_spk = torch.load(emb_upload_path)
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 1366, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 381, in default_restore_location
    result = fn(storage, location)
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 274, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "E:\Chat-TTSV3\Dlab\lib\site-packages\torch\serialization.py", line 258, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

究竟修改哪个目录下的哪个文件，可以解决这个问题呢？具体修改哪个语句呢？
折腾了好久，没搞定！求助大神，万分感谢！

备注：使用CPU模式下，如果不“上传音色”单击“生成”，一切正常； 一旦“上传音色”后单击“生成”，则出现上面的错误。求助大神指教

**Comment by CCmahua** [comment]
processors/audio_processor.py第38行修改为
```
 rand_spk = torch.load(emb_upload_path,map_location=torch.device('cpu'))
```

  processors/config_processor.py的save_config函数改为
```
def save_config(name,con_params: ConfigParams):
    con_params.tensor = get_seed_tensor(con_params.audio_seed)
    if con_params.custom_emb and con_params.emb_path is not None:
        con_params.tensor = torch.load(con_params.emb_path, map_location=torch.device('cpu'))
    save_path = os.path.join(get_path('CONFIG_DIR'), f"{name}.pt")
    torch.save(con_params, save_path)
    return f"配置保存至 {save_path}"
```
