### ISSUE TITLE
音频增强两个选项都报错

### ISSUE THREAD

**Issue by NeverOccurs** [CCmahua/ChatTTS-Enhanced#7]
Windows系统，提示NotImplementedError: cannot instantiate 'PosixPath' on your system

INFO:modules.enhance.enhancer.download:Downloading the model...
INFO:modules.enhance.enhancer.download:Repository already exists, attempting to pull latest changes...
Already up to date.
INFO:modules.enhance.enhancer.download:Pulling large files...
INFO:modules.enhance.hparams:Reading hparams from F:\Applications\ChatTTS-Enhanced\modules\enhance\model_repo\enhancer_stage2\hparams.yaml
Traceback (most recent call last):
  File "F:\Anaconda3\envs\chattts\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "F:\Anaconda3\envs\chattts\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\Anaconda3\envs\chattts\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "F:\Anaconda3\envs\chattts\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Anaconda3\envs\chattts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\Anaconda3\envs\chattts\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "F:\Anaconda3\envs\chattts\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "F:\Applications\ChatTTS-Enhanced\webui\output_option.py", line 95, in generate_audio
    original_audio_output,enhanced_audio_output, text = audio_pre_processor(audio_pre_Process_Params,enhance_parms,CHAT)
  File "F:\Applications\ChatTTS-Enhanced\processors\audio_processor.py", line 79, in audio_pre_processor
    enhanced_sample_rate, enhanced_audio_data = enhance_processor(enparams)
  File "F:\Applications\ChatTTS-Enhanced\processors\enhance_processors.py", line 25, in enhance_processor
    dwav, sr = denoise(dwav, sr, device)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Applications\ChatTTS-Enhanced\modules\enhance\enhancer\inference.py", line 29, in denoise
    enhancer = load_enhancer(run_dir, device)
  File "F:\Applications\ChatTTS-Enhanced\modules\enhance\enhancer\inference.py", line 17, in load_enhancer
    hp = HParams.load(run_dir)
  File "F:\Applications\ChatTTS-Enhanced\modules\enhance\hparams.py", line 109, in load
    hps.append(cls.from_yaml(run_dir / "hparams.yaml"))
  File "F:\Applications\ChatTTS-Enhanced\modules\enhance\hparams.py", line 94, in from_yaml
    return cls(**dict(OmegaConf.merge(cls(), OmegaConf.load(path))))
  File "F:\Anaconda3\envs\chattts\lib\site-packages\omegaconf\omegaconf.py", line 190, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\omegaconf\_utils.py", line 151, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "F:\Anaconda3\envs\chattts\lib\site-packages\omegaconf\_utils.py", line 183, in <lambda>
    lambda loader, node: pathlib.PosixPath(*loader.construct_sequence(node)),
  File "F:\Anaconda3\envs\chattts\lib\pathlib.py", line 962, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by CCmahua** [comment]
webui.py添加
```
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath
```

**Comment by AdamShuo** [comment]
> webui.py添加
> 
> ```
> import pathlib
> temp = pathlib.PosixPath
> pathlib.PosixPath = pathlib.WindowsPath
> ```

Linux下如何修改？

**Comment by CCmahua** [comment]
> > webui.py添加
> > ```
> > import pathlib
> > temp = pathlib.PosixPath
> > pathlib.PosixPath = pathlib.WindowsPath
> > ```
> 
> Linux下如何修改？

Linux下无需修改

**Comment by AdamShuo** [comment]
> > > webui.py添加
> > > ```
> > > import pathlib
> > > temp = pathlib.PosixPath
> > > pathlib.PosixPath = pathlib.WindowsPath
> > > ```
> > 
> > 
> > Linux下如何修改？
> 
> Linux下无需修改

可是我在云端linux下遇到同样错误
