### ISSUE TITLE
pip install resemble-enhance 安装报错

### ISSUE THREAD

**Issue by ccj** [CCmahua/ChatTTS-Enhanced#8]
Collecting deepspeed==0.12.4 (from resemble-enhance)
  Using cached deepspeed-0.12.4.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/c4/qjx8xh4s3w16yhfbvgjks0jw0000gn/T/pip-install-56b0ezhs/deepspeed_f255ca93b9dc46de8752f70b00fa45cf/setup.py", line 38, in <module>
          from op_builder.all_ops import ALL_OPS
        File "/private/var/folders/c4/qjx8xh4s3w16yhfbvgjks0jw0000gn/T/pip-install-56b0ezhs/deepspeed_f255ca93b9dc46de8752f70b00fa45cf/op_builder/all_ops.py", line 29, in <module>
          builder = get_accelerator().create_op_builder(member_name)
        File "/private/var/folders/c4/qjx8xh4s3w16yhfbvgjks0jw0000gn/T/pip-install-56b0ezhs/deepspeed_f255ca93b9dc46de8752f70b00fa45cf/accelerator/mps_accelerator.py", line 223, in create_op_builder
          builder_class = self.get_op_builder(op_name)
        File "/private/var/folders/c4/qjx8xh4s3w16yhfbvgjks0jw0000gn/T/pip-install-56b0ezhs/deepspeed_f255ca93b9dc46de8752f70b00fa45cf/accelerator/mps_accelerator.py", line 230, in get_op_builder
          from deepspeed.ops.op_builder.cpu import NotImplementedBuilder
        File "/private/var/folders/c4/qjx8xh4s3w16yhfbvgjks0jw0000gn/T/pip-install-56b0ezhs/deepspeed_f255ca93b9dc46de8752f70b00fa45cf/deepspeed/__init__.py", line 13, in <module>
          from packaging import version as pkg_version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by CCmahua** [comment]
windows去以下地址下载对应的`deepspeed-0.11.2+cuda118-cp310-cp310-win_amd64.whl`包
```
https://github.com/erew123/alltalk_tts/releases/tag/deepspeed
```
执行
```
pip install deepspeed-0.11.2+cuda118-cp310-cp310-win_amd64.whl
```

**Comment by godsoul** [comment]
macos 也报错

**Comment by godsoul** [comment]
pywrapfst.cc:594:10: fatal error: 'fst/util.h' file not found
      #include <fst/util.h>
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openfst
  Running setup.py clean for openfst
Failed to build openfst
ERROR: Could not build wheels for openfst, which is required to install pyproject.toml-based projects

**Comment by godsoul** [comment]
conda install -c conda-forge pynini=2.1.5
pip install WeTextProcessing  
这样解决了

**Comment by ccj** [comment]
谢谢了
